// This file is auto-generated by the user's request to create a new file.
// It is empty for now.
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../providers/theme_provider.dart';

class SettingsScreen extends ConsumerWidget {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final themeMode = ref.watch(themeProvider);
    final themeNotifier = ref.read(themeProvider.notifier);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Settings'),
      ),
      body: ListView(
        children: [
          ListTile(
            leading: const Icon(Icons.brightness_6),
            title: const Text('Dark Mode'),
            trailing: Switch(
              value: themeMode == ThemeMode.dark,
              onChanged: (value) {
                themeNotifier.setThemeMode(value ? ThemeMode.dark : ThemeMode.light);
              },
            ),
          ),
          ListTile(
            leading: const Icon(Icons.info),
            title: const Text('About'),
            subtitle: const Text('Pixelo v1.0.0'),
            onTap: () {
              showAboutDialog(
                context: context,
                applicationName: 'Pixelo',
                applicationVersion: '1.0.0',
                children: [
                  const Text('A beautiful Instagram clone demonstrating Flutter capabilities.'),
                ],
              );
            },
          ),
        ],
      ),
    );
  }
}
